# Generated by Django 3.1.5 on 2021-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210125_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(help_text='short description of the picture', max_length=200, null=True),
        ),
    ]
